from . import student_info
from . import standard_info
from . import teacher_info
from . import library_info
from . import cultural_info
from . import scholarship_info
from . import inheritfile
from . import sale_order
from . import product_template
from . import weather_info
from . import company_info
from . import account_move
from . import purchase_order
